var name = 'Joshua';
var latter =
    "Ipsum nostrud cillum non irure mollit ea consequat non ut \n\neu deserunt sunt eiusmod consequat. Veniam excepteur consequat sit commodo irure enim esse id elit sit proident qui. Aliquip amet magna esse et dolore aliquip elit minim reprehenderit laborum voluptate minim. Sit nostrud elit reprehenderit est aliquip duis. Eiusmod sunt incididunt culpa ad qui sint nisi non pariatur. "+ name +" In in excepteur Lorem tempor deserunt eu enim ea incididunt proident do amet cupidatat. Est sunt laboris proident sint laborum non. Occaecat veniam nostrud elit occaecat. Qui voluptate mollit excepteur excepteur aute exercitation nulla. Elit eu cillum ut qui aliqua ut deserunt qui ipsum sint tempor. Quis nulla ipsum veniam sit. Proident ullamco tempor occaecat elit labore. Excepteur in sint officia sit culpa est labore ea velit dolor fugiat. Officia ullamco sint est eu est veniam incididunt voluptate ex. Ea enim elit exercitation esse est voluptate consequat deserunt irure incididunt exercitation. Sunt aliqua in consectetur laboris.Nulla tempor aliquip culpa ea ea non elit.Cillum magna aliquip ex in .Magna duis ex occaecat proident tempor cupidatat.Excepteur ullamco ex do aliqua ullamco anim velit occaecat sunt quis.Officia duis aute laboris excepteur minim nostrud tempor incididunt ex.Nisi dolor exercitation irure consectetur exercitation veniam duis.Cillum ea non quis sit nisi est enim eu dolore irure reprehenderit.Deserunt culpa consectetur esse non elit quis sint non consequat.Consectetur commodo anim consectetur enim esse laborum reprehenderit reprehenderit cillum ad nisi commodo.Velit id adipisicing ex consectetur do aliquip.Duis sit irure ad ex ad elit quis reprehenderit ut eiusmod non quis.Non nostrud qui aliqua non ea.Pariatur esse eiusmod occaecat deserunt consequat cillum excepteur voluptate.Sint non elit et ipsum incididunt ad labore ea.Deserunt mollit occaecat ad excepteur labore ipsum.Eiusmod qui incididunt minim ad dolor deserunt dolor enim reprehenderit pariatur ipsum.Deserunt esse excepteur nostrud est.Non aliquip ullamco pariatur exercitation in cillum labore.Consequat minim occaecat ea sint eiusmod exercitation ut.Id id ut incididunt nisi magna nostrud.Sint reprehenderit eiusmod sunt magna nulla ut aliqua velit.Aute incididunt pariatur cillum amet magna.Sunt officia eu ut reprehenderit ut incididunt dolor nostrud incididunt.Pariatur enim laborum anim nisi proident.Consequat reprehenderit fugiat aliquip aliquip et cupidatat occaecat eiusmod fugiat duis laborum enim aute proident.Proident exercitation consequat ipsum esse.Labore eiusmod sunt reprehenderit excepteur quis tempor.Aliquip incididunt nostrud amet esse dolore do Lorem id aliqua qui ullamco.Minim esse aliquip ipsum do anim aliquip aliqua non qui consequat aliqua.Sit ut nulla do elit officia consectetur ullamco fugiat aliquip eiusmod qui qui";

var champ = 
`Ipsum nostrud cillum ${name} ${1+6}

non irure mollit ea consequat non ut eu deserunt sunt eiusmod consequat. Veniam excepteur consequat sit commodo irure enim esse id elit sit proident qui. Aliquip amet magna esse et dolore aliquip elit minim reprehenderit laborum voluptate minim. Sit nostrud elit reprehenderit est aliquip duis. Eiusmod sunt incididunt culpa ad qui sint nisi non pariatur. In in excepteur Lorem tempor deserunt eu enim ea incididunt proident do amet cupidatat. Est sunt laboris proident sint laborum non. Occaecat veniam nostrud elit occaecat. Qui voluptate mollit excepteur excepteur aute exercitation nulla. Elit eu cillum ut qui aliqua ut deserunt qui ipsum sint tempor. Quis nulla ipsum veniam sit. Proident ullamco tempor occaecat elit labore. Excepteur in sint officia sit culpa est labore ea velit dolor fugiat. Officia ullamco sint est eu est veniam incididunt voluptate ex. Ea enim elit exercitation esse est voluptate consequat deserunt irure incididunt exercitation. Sunt aliqua in consectetur laboris.Nulla tempor aliquip culpa ea ea non elit.Cillum magna aliquip ex in .Magna duis ex occaecat proident tempor cupidatat.Excepteur ullamco ex do aliqua ullamco anim velit occaecat sunt quis.Officia duis aute laboris excepteur minim nostrud tempor incididunt ex.Nisi dolor exercitation irure consectetur exercitation veniam duis.Cillum ea non quis sit nisi est enim eu dolore irure reprehenderit.Deserunt culpa consectetur esse non elit quis sint non consequat.Consectetur commodo anim consectetur enim esse laborum reprehenderit reprehenderit cillum ad nisi commodo.Velit id adipisicing ex consectetur do aliquip.Duis sit irure ad ex ad elit quis reprehenderit ut eiusmod non quis.Non nostrud qui aliqua non ea.Pariatur esse eiusmod occaecat deserunt consequat cillum excepteur voluptate.Sint non elit et ipsum incididunt ad labore ea.Deserunt mollit occaecat ad excepteur labore ipsum.Eiusmod qui incididunt minim ad dolor deserunt dolor enim reprehenderit pariatur ipsum.Deserunt esse excepteur nostrud est.Non aliquip ullamco pariatur exercitation in cillum labore.Consequat minim occaecat ea sint eiusmod exercitation ut.Id id ut incididunt nisi magna nostrud.Sint reprehenderit eiusmod sunt magna nulla ut aliqua velit.Aute incididunt pariatur cillum amet magna.Sunt officia eu ut reprehenderit ut incididunt dolor nostrud incididunt.Pariatur enim laborum anim nisi proident.Consequat reprehenderit fugiat aliquip aliquip et cupidatat occaecat eiusmod fugiat duis laborum enim aute proident.Proident exercitation consequat ipsum esse.Labore eiusmod sunt reprehenderit excepteur quis tempor.Aliquip incididunt nostrud amet esse dolore do Lorem id aliqua qui ullamco.Minim esse aliquip ipsum do anim aliquip aliqua non qui consequat aliqua.Sit ut nulla do elit officia consectetur ullamco fugiat aliquip eiusmod qui qui`;

console.log(latter);

console.log(champ);